title: Eigenbau LED Matrix Display für Solar Manager
description: Firmware für ein Adafruit LED Display, welches Solar Manager Werte anzeigt.

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag

kramdown:
  parse_block_html: true